# Site settings
title: Pascal Schulthess
description: 'System Biologist and Control Theorist'
url: 'http://pascal.schulthess.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'pascalschulthess'

author:
  name: 'Pascal Schulthess'
  twitter_username: hellopascal
#  facebook_username: hellopascalschulthess
  github_username:  pascalschulthess
  linkedin_username:  pascalschulthess
  researchgate_username: Pascal_Schulthess2
  instagram_username: pascalschulthess
  orcid_username: 0000-0002-7768-8507
  slideshare_username: PascalSchulthess1

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
timezone: Europe/Amsterdam

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
